#!/usr/bin/env python3
"""
Apply reviewed AI translations (仅 d 字段) back into the AI cache and the final apm-param-db.json.

Usage (after human review of a translations.review.*.json file):
  python tools/apply-reviewed-translations.py path/to/translations.review.20260529-....json --dry-run
  python tools/apply-reviewed-translations.py path/to/translations.review.20260529-....json

The script will:
- Only process items whose "status" is "accepted" or where the user has provided a final "accepted" translation.
- Update the AI cache (apm-param-translate-cache.ai.json)
- Merge the translations into the target db while preserving grp / grpBySrc and all other metadata.
- Create a backup of the db before writing (unless --skip-backup).

Review file format (generated by translate_params_ai.py --review):
{
  "items": [
    {
      "id": "...",
      "param": "ACRO_YAW_RATE",
      "field": "d",
      "source": "English text...",
      "proposed": "AI proposed Chinese...",
      "status": "pending"   // change to "accepted" or provide "accepted" field, or delete the item
    }
  ]
}
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "JS" / "data" / "apm-param-db.json"
AI_CACHE_PATH = ROOT / "JS" / "data" / "apm-param-translate-cache.ai.json"
BACKUP_DIR = ROOT / "tools" / "translation-review" / "backups"


def load_json(p: Path) -> dict[str, Any]:
    return json.loads(p.read_text(encoding="utf-8"))


def save_json(p: Path, obj: Any) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Apply reviewed d-field translations")
    ap.add_argument("review_file", type=Path, help="Path to a translations.review.*.json file")
    ap.add_argument("--db", type=Path, default=DB_PATH, help="Target apm-param-db.json")
    ap.add_argument("--cache", type=Path, default=AI_CACHE_PATH, help="AI translation cache")
    ap.add_argument("--dry-run", action="store_true", help="Show what would be done, do not write files")
    ap.add_argument("--skip-backup", action="store_true", help="Do not create a backup of the db")
    args = ap.parse_args()

    review_path = args.review_file
    if not review_path.is_file():
        print(f"Review file not found: {review_path}", file=sys.stderr)
        sys.exit(1)

    review = load_json(review_path)
    items = review.get("items", [])
    if not items:
        print("No items in review file.")
        return

    # Collect accepted translations
    accepted: dict[str, str] = {}   # cache_key -> translation
    for it in items:
        if not isinstance(it, dict):
            continue
        field = it.get("field")
        if field != "d":
            continue  # we only care about d in this workflow

        status = (it.get("status") or "").lower()
        source = it.get("source", "").strip()
        proposed = it.get("proposed", "").strip()
        accepted_text = it.get("accepted", "").strip()

        final = accepted_text or (proposed if status in ("accepted", "approve", "ok", "yes") else "")
        if not final or not source:
            continue

        cache_key = f"{field}\t{source}"
        accepted[cache_key] = final

    if not accepted:
        print("No accepted d-translations found in the review file.")
        return

    print(f"Found {len(accepted)} accepted d-translations.")

    cache = {}
    if args.cache.is_file():
        try:
            cache = load_json(args.cache)
        except Exception as e:
            print(f"Warning: failed to read cache ({e}), starting fresh for this apply.")

    # Merge into cache
    cache.update(accepted)
    print(f"Cache will have {len(cache)} entries after merge.")

    if args.dry_run:
        print("\n[DRY RUN] Would update cache and db. No files written.")
        for k in list(accepted.keys())[:5]:
            print(f"  {k[:60]}... -> {accepted[k][:60]}...")
        if len(accepted) > 5:
            print(f"  ... and {len(accepted)-5} more")
        return

    # Write cache
    save_json(args.cache, cache)
    print(f"Updated cache: {args.cache}")

    # Apply to db
    if not args.db.is_file():
        print(f"Target db not found: {args.db}", file=sys.stderr)
        sys.exit(2)

    # Backup
    if not args.skip_backup:
        BACKUP_DIR.mkdir(parents=True, exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup_path = BACKUP_DIR / f"apm-param-db.pre-apply-{ts}.json"
        shutil.copy2(args.db, backup_path)
        print(f"Backup created: {backup_path}")

    db = load_json(args.db)

    applied = 0
    for value in db.values():
        if not isinstance(value, dict):
            continue
        d_src = value.get("d")
        if not isinstance(d_src, str):
            continue
        key = f"d\t{d_src.strip()}"
        if key in accepted:
            value["d"] = accepted[key]
            applied += 1

    save_json(args.db, db)
    print(f"Applied {applied} d-translations to {args.db}")
    print("Done.")


if __name__ == "__main__":
    main()